config/routes.rb
Rails.application.routes.draw do
  resources :volunteers, only:[:new, :create, :show, :edit, :update, :destroy]
  patch '/trips/complete', to: 'trips#complete', as: 'complete'
  resources :trips, only:[:create, :show, :index]
  get '/food_banks/data', to: 'food_banks#data', as: "data"
  resources :food_banks, only:[:new, :create, :show]
  patch '/trips/:id', to: 'trips#update', as: 'update_trip'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  delete '/login', to: 'logins#destroy', as: 'logout'
  root 'application#home'
end

app/views/layouts/_header.erb
<nav class="navbar navbar-light" style="background-color: #034f00;">
    <div class="container">
        <ul class="nav">
            <svg xmlns="http://www.w3.org/2000/svg" width="70" height="63" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16" style="padding-right:15px; color: #CBDECA">
                <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
            </svg>
            <h1><%=link_to "Food Connect", root_path, :style=>"text-decoration: none; color: #cbdeca; font-family: 'Abril Fatface', cursive; font-size: 55px"%></h1>
        </ul>
      <%if session[:username] %>
            <ul class="nav justify-content-end">
                <li class="nav-item" style="margin-right: 40px; text-decoration: none; color: #cbdeca;"><h5>Welcome, <%=link_to @user.name, @user, :style=>"color: #cbdeca;"%></h5></li>
                <li class="nav-item"><%=button_to "Logout", logout_path, method: :delete, :class=>"btn btn-outline-success"%></li>
            </ul>
        <%else%>
            <ul class="nav justify-content-end">
                <li class="nav-item" style="margin-right: 40px;"><h5><%= link_to "Login", login_path, method: :get, :style=>"text-decoration: none; color: #cbdeca;"%></h5></li>
                <li class="nav-item" style="margin-right: 40px;"><h5><%= link_to "Volunteer Register", new_volunteer_path, method: :get, :style=>"text-decoration: none; color: #cbdeca;"%></h5></li> 
                <li class="nav-item"><h5><%= link_to "Food Bank Register", new_food_bank_path, method: :get, :style=>"color: #cbdeca; text-decoration: none;"%></h5></li>

            </ul>
        <%end%>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Potta+One&display=swap" rel="stylesheet">
  
  </head>
  <body style="background-image: url(https://cdn.hipwallpaper.com/m/65/38/laWyuj.jpg); background-size:cover;">
    <%= render "layouts/header"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>